CREATE TABLE `tabela_protesto` (
  `id_codigo_cartorio` varchar(20) NOT NULL,
  `documento` varchar(20) NOT NULL,
  `datahora` varchar(20) NOT NULL,
  `identificador` varchar(30) NOT NULL,
  `tipo_documento` int(11) DEFAULT NULL,
  `nome_devedor` varchar(200) DEFAULT NULL,
  `endereco_devedor` varchar(200) DEFAULT NULL,
  `cep_devedor` varchar(50) DEFAULT NULL,
  `bairro_devedor` varchar(50) DEFAULT NULL,
  `cidade_devedor` varchar(50) DEFAULT NULL,
  `uf_devedor` varchar(2) DEFAULT NULL,
  `livro_protesto` varchar(50) DEFAULT NULL,
  `folha_protesto` varchar(50) DEFAULT NULL,
  `protocolo` varchar(50) DEFAULT NULL,
  `data_protocolo` varchar(50) DEFAULT NULL,
  `especie` varchar(10) DEFAULT NULL,
  `numero_titulo` varchar(50) DEFAULT NULL,
  `data_emissao` varchar(50) DEFAULT NULL,
  `data_vencimento` varchar(50) DEFAULT NULL,
  `data_protesto` varchar(50) DEFAULT NULL,
  `valor_original` varchar(50) DEFAULT NULL,
  `valor_protestado` varchar(50) DEFAULT NULL,
  `data_inclusao` varchar(50) DEFAULT NULL,
  `data_inativacao` varchar(50) DEFAULT NULL,
  `data_consulta_detalhada` varchar(50) DEFAULT NULL,
  `data_retorno_consulta_detalhada` varchar(50) DEFAULT NULL,
  `retorno_consulta` longtext,
  `status` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id_codigo_cartorio`,`documento`,`datahora`,`identificador`),
  KEY `idx_tabela_protesto` (`documento`),
  KEY `idx02_tabela_protesto` (`documento`,`data_inativacao`),
  KEY `indx01_doc_status` (`documento`,`status`),
  KEY `indx01_id_codigo_cartorio` (`id_codigo_cartorio`),
  KEY `indx02_status` (`status`),
  KEY `indx_data_inclusao` (`data_inclusao`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
